### ISSUE TITLE
ddd 스터디 정리

### ISSUE THREAD

**Issue by chanhyeong** [chanhyeong/study#1]
## 1. 왜 모았는지?
분야가 다른 개인이 각자하고 공유 중이었는데  
ddd 를 들어가려고 보니 개인 공부 + 공유보단 무언가 토론이 있으면 좋을 것 같다

#### 기존에 진행한 방식
- 각자 주제를 잡고 한 주 동안 무엇을 했는지 공유
- 형식은 자유
  - md 로 정리
  - 어떤 알고리즘을 어떻게 했는지 공유
  - 코드 공유
  - ....
- 궁금한 점이 있으면 서로 질문주고 받음

#### 무엇을 하려는지
- ddd 를 애매하게 알고 있는 상태 or 모르는 상태라고 가정하고
- 1주 단위로
  - 1 ~ 2장을 읽기
  - 정리를 하는 것은 개인의 자유이지만 3번 참고
- (개인) 이 레포에 기록할 예정

#### 지양하려는 것
- 한 주 동안 각자 특정 파트를 정리해서 발표하기
  - 맡은 파트가 아니면 읽지 않게 되거나 할 수 있음 -> 남는게 없음

## 3. 어떻게 할 것 인지?
- 금요일 4~5시
  - 평일엔 배포 일정으로 안될 수도
  - 5시 이후엔 개인 일정이 있을 수도
  - 그냥 친구들이었으면 주말에 하자고...
- 사회자?
  - 돌아가면서 한 주의 진행을 맡음
  - 사회자가 한 주 읽은 내용들을 리뷰하고 (너무한가..?)
  - 자유롭게 생각하고 있는 내용을 말하기
- 한 주에 나온 이야기에 대한 정리?
- 추가 의견
- 화상회의 툴
  1. whale on
      - 무료
      - 경험 상 화면 공유 품질이 좋지 않음(2~3개월 전), 현재는 잘 모르겠음
  2. zoom
      - 40분마다 끊어짐
  3. works
      - vpn 연결이 필요한 것으로 알고 있음
      - 어차피 업무시간에 하는거여서 상관 없을 듯
- 진도
  - 1주에 1장? 2장?

#### 휴가 시 (금요일이어서..)
- 목요일로 이동
- 한 주 쉬고
  - 전체 일정 1주 연장 
  - 그 다음주에 2주치 진행

**Comment by chanhyeong** [comment]
전체 11주

단순 페이지 수 기준으로 나눠보면

|주차|장|
|||
|||
|||
|||
|||

**Comment by chanhyeong** [comment]
전체 11주

단순 페이지 수 기준으로 나눠보면

| 주차 | 장 | 담당 |
| - | - | - |
| 1 | 1, 2, 3 | @chanhyeong |
|2| 4 |  |
|3| 5 |  |
|4| 6 |  |
|5| 7, 8 |  |
|6| 9 |  |
|7| 10 |  |
|8| 11, 12 |  |
|9| 13, 14 중간 |  |
|10| 14 끝 |  |
|11| 15 |  |
|12| 16 |  |
|13| 17 |  |

**Comment by chanhyeong** [comment]
첫 주만 1~3 을 해보고
보고 다음 분량을 정해보자

**Comment by chanhyeong** [comment]
organization 이름 공모

**Comment by y2o2u2n** [comment]
기록 제안

1) 깃헙 단체를 만들고 레포 하나 만든 후에
2) 각 챕터별로 이슈 하나를 만든 후에
3) 각자 간단하게 자유롭게 정리 (안해도 됨 ㅎㅎ)

**Comment by chanhyeong** [comment]
1명은 이슈에 참여
2명 이상이면 일정 조정

**Comment by y2o2u2n** [comment]
이름 제안

막 던지겠습니당

- n kids
- no dev study

**Comment by chanhyeong** [comment]
ddd 만 할거면
- juniors-ddd-study

ddd 이후를 더 본다면
- juniors-study

**Comment by chanhyeong** [comment]
https://github.com/juniors-dev-study/domain-driven-design 로 이동하여 진행
